services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2019-CU28-ubuntu-20.04"
    entrypoint: /mssql/entrypoint.sh
    command: /opt/mssql/bin/sqlservr
    environment:
      SA_PASSWORD: "Your_password123!"
      ACCEPT_EULA: "Y"
    volumes:
      - ./mssql:/mssql
    ports:
      - "15785:1433"
    healthcheck:
        # The OPENCoronaTempTables database is initialised last, so check that
        # we can connect to that db specifically
        test: /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "Your_password123!" -d "OPENCoronaTempTables" -Q "SELECT 1" || exit 1
        interval: 10s
        timeout: 3s
        retries: 10
        start_period: 10s

  prod-test:
    build:
      context: .
    entrypoint: scripts/run-tests.sh
    environment:
      DATABASE_URL: "mssql://SA:Your_password123!@mssql:1433/Test_OpenCorona"
    depends_on:
      mssql:
        condition: service_healthy
